// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mikeka.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mikeka.Api.Data.Migrations
{
    [DbContext(typeof(MikekaDb))]
    [Migration("20261007100838_AccountMaxPicks")]
    partial class AccountMaxPicks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mikeka.Api.Domain.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseStake")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("LastBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<List<string>>("Leagues")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("LossStreak")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxCombinedOdds")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)");

                    b.Property<int>("MaxLosses")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxPickOdds")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)");

                    b.Property<int>("MaxPicks")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinCombinedOdds")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)");

                    b.Property<decimal>("MinPickOdds")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordProtected")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Stopped")
                        .HasColumnType("boolean");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Url", "Username")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Mikeka.Api.Domain.BalanceEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "At");

                    b.ToTable("BalanceHistory");
                });

            modelBuilder.Entity("Mikeka.Api.Domain.BettingSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("CheckIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<List<string>>("ExcludedTeams")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("MatchMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxCombinedOdds")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)");

                    b.Property<int>("MaxDaysAhead")
                        .HasColumnType("integer");

                    b.Property<int>("MaxLosses")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxPickOdds")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)");

                    b.Property<decimal>("MinCombinedOdds")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)");

                    b.Property<decimal>("MinPickOdds")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)");

                    b.Property<int>("SameSiteDelayMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("SettlementGapMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckIntervalMinutes = 60,
                            ExcludedTeams = new List<string>(),
                            MatchMinutes = 180,
                            MaxCombinedOdds = 2.20m,
                            MaxDaysAhead = 7,
                            MaxLosses = 4,
                            MaxPickOdds = 1.20m,
                            MinCombinedOdds = 2.10m,
                            MinPickOdds = 1.10m,
                            SameSiteDelayMinutes = 5,
                            SettlementGapMinutes = 60,
                            UpdatedAt = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Mikeka.Api.Domain.RunLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("RunLogs");
                });

            modelBuilder.Entity("Mikeka.Api.Domain.Slip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("BalanceBefore")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("BetDay")
                        .HasColumnType("date");

                    b.Property<string>("BetReference")
                        .HasColumnType("text");

                    b.Property<decimal>("CombinedOdds")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<decimal>("PotentialReturn")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("ResultCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<DateTime>>("SettlementChecks")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]");

                    b.Property<decimal>("Stake")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "BetDay");

                    b.ToTable("Slips");
                });

            modelBuilder.Entity("Mikeka.Api.Domain.SlipPick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Away")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Home")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Interval")
                        .HasColumnType("text");

                    b.Property<DateTime>("Kickoff")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Line")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Odds")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SlipId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SlipId");

                    b.ToTable("SlipPicks");
                });

            modelBuilder.Entity("Mikeka.Api.Domain.Account", b =>
                {
                    b.OwnsMany("Mikeka.Api.Domain.MarketChoice", "Markets", b1 =>
                        {
                            b1.Property<int>("AccountId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int?>("IntervalFrom")
                                .HasColumnType("integer");

                            b1.Property<int?>("IntervalTo")
                                .HasColumnType("integer");

                            b1.Property<List<string>>("Leagues")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<decimal?>("Line")
                                .HasColumnType("numeric");

                            b1.Property<string>("Market")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Side")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AccountId", "Id");

                            b1.ToTable("Accounts");

                            b1.ToJson("Markets");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("Markets");
                });

            modelBuilder.Entity("Mikeka.Api.Domain.Slip", b =>
                {
                    b.HasOne("Mikeka.Api.Domain.Account", "Account")
                        .WithMany("Slips")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Mikeka.Api.Domain.SlipPick", b =>
                {
                    b.HasOne("Mikeka.Api.Domain.Slip", null)
                        .WithMany("Picks")
                        .HasForeignKey("SlipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mikeka.Api.Domain.Account", b =>
                {
                    b.Navigation("Slips");
                });

            modelBuilder.Entity("Mikeka.Api.Domain.Slip", b =>
                {
                    b.Navigation("Picks");
                });
#pragma warning restore 612, 618
        }
    }
}
